# Generated by Django 2.2.7 on 2019-11-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
